language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - ./build.sh
matrix:
  allow_failures:
    # nightly fails too often due to clippy/fmt not being available
    - rust: nightly
  fast_finish: true
