[package]
name = "my_new_project"
version = "0.1.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
lazy_static = "1.3.0"
regex = "1.1.6"
chrono = { version = "0.4.6", features = ["serde"] }
chrono-tz = { version = "0.5.1", features = ["serde"] }
