[package]
name = "my_new_project"
version = "0.1.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]
edition = "2018"
build = "build/build.rs"

[[bin]]
name = "my_new_project"
path = "src/main.rs"

[dependencies]
# Utilities
rand = "^0.6.5"
lazy_static = "^1.3.0"
regex = "^1.1.6"
chrono = { version = "^0.4.6", features = ["serde"] }
chrono-tz = { version = "^0.5.1", features = ["serde"] }
itertools = "^0.8.0"
generic-array = "^0.13.0"
array_tool = "^1.0.3"
configure_me = "^0.3.1"
directories = "^1.0.2"
serde = "1"  # TODO version, tests

# Application
#diesel



[build-dependencies]
configure_me_codegen = "^0.3.2"
