#!/usr/bin/env sh

###
### Run cargo command using a Docker image, in case rust/cargo are not installed.
###

set -eEu
cache_dir="$(dirname $(mktemp))/$USER/{{crate_name}}"
mkdir -m700 -p "$cache_dir"
docker run --rm \
    -v"$(pwd)":/volume \
    -it "mverleg/rust_nightly_musl_base:deps_2021-12-25_4" cargo "$@"
# -v"$cache_dir":/root/.cargo
