#!/usr/bin/env sh

###
### Run cargo command using a Docker image, in case rust/cargo are not installed.
###

set -eEu
cache_dir="$(dirname $(mktemp))/$USER/{{crate_name}}"
mkdir -m700 -p "$cache_dir"
docker run --rm \
    -v"$(pwd)":/volume -v"$cache_dir":/root/.cargo/ \
    -it "mverleg/rust_nightly_musl_base:nodeps_2021-12-15_22" cargo "$@"

