
name: Dependencies - dependencies are up to date and do not conflcit
on:
  schedule:
    - cron: '0 17 * * 6'
  pull_request:
  release:
    types:
      - created

jobs:
  polished:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check dependencies
        run: |
          ci/check_dependencies.sh
