
# This is intended to be an addition to 'works.yml', which should always run when these jobs run.
# These checks (along with 'works.yml') should all pass before merging to a shared branch (including master) or reviewing.
name: Polished - style guidelines followed, no suspicious patterns, dependencies up to date, documented.
on:
  pull_request:
  release:
    types:
      - created

jobs:
  polished:
    name: Polished
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check code style
        run: |
          ci/check_style.sh
      - name: Lint
        run: |
          ci/check_style.sh
      - name: Check performance
        run: |
          ci/check_performance.sh
      - name: Build documentation
        run: |
          ci/build_docs.sh
