
# This is intended to be an addition to 'works.yaml', which should always run when these jobs run.
# These checks (along with 'works.yaml') should all pass before merging to a shared branch (including master) or reviewing.
name: Polished - style guidelines followed, no suspicious patterns, dependencies up to date, documented.
on:
  pull_request:
  release:
    types:
      - created

jobs:
  check_style:
    name: check_style
    steps:
      script: "ci/check_style.sh"
  check_lint:
    name: check_lint
    steps:
      script: "ci/check_lint.sh"
  check_performance:
    name: check_performance
    steps:
      script: "ci/check_performance.sh"
  build_docs:
    name: build_docs
    steps:
      script: "ci/build_docs.sh"
